name: Generate Java Documentation

'on':
  pull_request:
    types: closed
    branches:
      - main

jobs:
  documentation:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Generate Javadoc
        run: mvn -B javadoc:javadoc -DdestDir=target/site/apidocs

      - name: Check generated documentation
       run: |
          echo "=== TARGET DIRECTORY ==="
          ls -la target || true
          echo "=== ALL TARGET CONTENT ==="
          find target -type f -print || true
          echo "=== ALL DIRECTORIES ==="
          find target -type d -print || true

     # - name: Deploy documentation
       # uses: peaceiris/actions-gh-pages@v4
       # with:
         # github_token: ${{ secrets.GITHUB_TOKEN }}
         # publish_dir: ./target/site/apidocs
